name: list_ext
description: Dart extension methods for Iterable and List. You can easily sum, count elements and many more.
version: 0.1.1
homepage: https://github.com/innim/

environment:
  sdk: ">=2.6.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.14.2