name: list_ext
description: Dart extension methods for Iterable and List. You can easily sum, count elements and many more.
version: 0.1.2+1
homepage: https://github.com/innim/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  quiver: ^2.0.0

dev_dependencies:
  test: ^1.14.2