name: list_ext
version: 0.0.1
description: Dart extension methods for Iterable and List. You can easily sum, count elements and mony more.
author: Innim
homepage: https://github.com/innim/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
