name: list_ext
description: Dart extension methods for Iterable and List. You can easily sum, count elements and many more.
version: 1.0.4
homepage: https://github.com/innim/
repository: https://github.com/Innim/dart_list_extensions
issue_tracker: https://github.com/Innim/dart_list_extensions/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quiver: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.0
  innim_lint: ^0.1.3
